-- Create scores table for global leaderboards
CREATE TABLE IF NOT EXISTS public.scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_name TEXT NOT NULL CHECK (char_length(player_name) <= 16),
    car_id TEXT NOT NULL,
    track_id TEXT NOT NULL,
    time_ms INT NOT NULL CHECK (time_ms > 0),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for fast leaderboard queries per track
CREATE INDEX IF NOT EXISTS idx_scores_track_time ON public.scores (track_id, time_ms ASC);

-- Enable Row Level Security
ALTER TABLE public.scores ENABLE ROW LEVEL SECURITY;

-- Allow public read access to scores
CREATE POLICY "Allow public select" ON public.scores
    FOR SELECT USING (true);

-- Allow public insert access to submit scores
CREATE POLICY "Allow public insert" ON public.scores
    FOR INSERT WITH CHECK (true);
